#!/usr/local/bin/python

# Copyright 2017 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import print_function
import sys
import json
import jsonschema
from jsonschema import validate

with open('create-account.request.schema.json') as schema_file:
  schema = json.loads(schema_file.read())
  print("Testing use of ICD001 v 1.2 draft schema for data validation.")

  # The data to be validated:
  with open(sys.argv[1]) as data_file:
    jsn = json.loads(data_file.read())
    print("Input data:")
    print(json.dumps(jsn, indent=4))
    print("Validating the input data using jsonschema:")
    try:
      validate(jsn, schema)
      print("Validation completes successfully")
    except jsonschema.exceptions.ValidationError as ve:
      sys.stderr.write(str(ve) + "\n")

